// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgpWkCcSpR1ZjaWQiUu3irV93QoSPBE0g',
    appId: '1:261130355894:web:ecae365b03f4c095559217',
    messagingSenderId: '261130355894',
    projectId: 'tasknest-d79d0',
    authDomain: 'tasknest-d79d0.firebaseapp.com',
    storageBucket: 'tasknest-d79d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8tYtxwaiczmm2fPLWL7Jda3-B-EUuPSU',
    appId: '1:261130355894:android:a167707d284d92db559217',
    messagingSenderId: '261130355894',
    projectId: 'tasknest-d79d0',
    storageBucket: 'tasknest-d79d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcCZh0M8NpmCJskyCQ6YsZOEGbvgdt1-0',
    appId: '1:261130355894:ios:35d654995c9637b9559217',
    messagingSenderId: '261130355894',
    projectId: 'tasknest-d79d0',
    storageBucket: 'tasknest-d79d0.firebasestorage.app',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9iVn-6Ph5fLkQ2_5e3trgE67Spmri9jY',
    appId: '1:727830725517:ios:6f0305078332755a9b33c4',
    messagingSenderId: '727830725517',
    projectId: 'todolist-10ef1',
    storageBucket: 'todolist-10ef1.appspot.com',
    iosBundleId: 'com.example.flutterToDoList.RunnerTests',
  );
}